[package]
name = "liquent-storage"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "pipeline liquent storage"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
alloy-primitives.workspace = true
revm.workspace = true
reth-payload-builder.workspace = true
reth-storage-api.workspace = true
reth-evm.workspace = true
reth-revm.workspace = true
reth-trie.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-trie-parallel.workspace = true
reth-db-api.workspace = true

tracing.workspace = true
tokio.workspace = true
thiserror.workspace = true
once_cell.workspace = true
reth-metrics.workspace = true
metrics.workspace = true

[dev-dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
reth-chainspec.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
