[package]
name = "liquent-primitives"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Common types in liquent-reth."

[lints]
workspace = true

[dependencies]

[features]
config-from-env = []
