{
 "title": "Liquent Reth - Node Performance",
 "description": "Liquent Reth - Node  Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(reth_process_cpu_seconds_total,instance)"
    }
   },
   { "name": "quantile", "label": "quantile", "query": "0,0.5,0.9,0.95,0.99,0.999,1" }
  ]
 },
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_jemalloc_active{instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "reth_jemalloc_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "reth_jemalloc_mapped{instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "reth_jemalloc_metadata{instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "reth_jemalloc_resident{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "reth_jemalloc_retained{instance=~\"$instance\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "node_process_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_process_resident_memory_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Table Entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "reth_db_table_entries{instance=\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "title": "Liquent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Transaction TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(reth_transaction_pool_removed_transactions[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "levm metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_levm_total_tx_cnt{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "num_block_txs"
    },
    {
     "expr": "reth_levm_validation_cnt{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation_incarnations"
    },
    {
     "expr": "reth_levm_execution_cnt{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution_incarnations"
    },
    {
     "expr": "reth_levm_conflict_by_miner{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "conflict_by_miner&destruct"
    },
    {
     "expr": "reth_levm_one_attempt_with_dependency{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "one_attempt_txs"
    },
    {
     "expr": "reth_levm_more_attempts_with_dependency{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "more_attempt_txs"
    },
    {
     "expr": "reth_levm_conflict_txs{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "conflict_txs"
    },
    {
     "expr": "reth_levm_dependency_distance{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "dependency_distance"
    },
    {
     "expr": "reth_levm_conflict_cnt{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "conflict_incarnations"
    }
   ]
  },
  {
   "title": "Storage Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_storage_cache_num_items{instance=\"$instance\"}",
     "legendFormat": "cache_num_items"
    },
    {
     "expr": "reth_storage_block_cache_hit_ratio{instance=\"$instance\"}",
     "legendFormat": "block_cache_hit_ratio"
    },
    {
     "expr": "reth_storage_trie_cache_hit_ratio{instance=\"$instance\"}",
     "legendFormat": "trie_cache_hit_ratio"
    }
   ]
  },
  {
   "title": "block size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_levm_total_tx_cnt{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "num_block_txs - P({{quantile}})"
    },
    {
     "expr": "sum(rate(reth_levm_total_tx_cnt_sum{instance=~\"$instance\"}[$__rate_interval])) / sum(rate(reth_levm_total_tx_cnt_count{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg_num_block_txs"
    }
   ]
  },
  { "title": "Pipe Execution Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Merklize Duration Per Block",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_merklize_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "merklize_duration - P({{quantile}})"
    },
    {
     "expr": "sum(rate(reth_pipe_exec_layer_merklize_duration_sum{instance=~\"$instance\"}[$__rate_interval])) / sum(rate(reth_pipe_exec_layer_merklize_duration_count{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg_merklize_duration"
    },
    {
     "expr": "reth_pipe_exec_layer_cache_trie_state{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "cache_trie_state_time - P({{quantile}})"
    }
   ]
  },
  {
   "title": "Execute Duration Per Block",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_execute_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution_duration - P({{quantile}})"
    },
    {
     "expr": "sum(rate(reth_pipe_exec_layer_execute_duration_sum[$__rate_interval])) / sum(rate(reth_pipe_exec_layer_execute_duration_count[$__rate_interval]))",
     "legendFormat": "avg_execute_duration"
    },
    {
     "expr": "reth_pipe_exec_layer_cache_account_state{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "cache_account_state_time - P({{quantile}})"
    }
   ]
  },
  {
   "title": "Levm Execute Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "reth_levm_execution_time{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "levm_execution_time - P({{quantile}})"
    },
    {
     "expr": "reth_levm_commit_time{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "levm_commit_time - P({{quantile}})"
    },
    {
     "expr": "reth_levm_total_time{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "levm_total_time - P({{quantile}})"
    },
    {
     "expr": "sum(rate(reth_levm_total_time_sum{instance=\"$instance\"}[$__rate_interval])) / sum(rate(reth_levm_total_time_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg_total_time"
    },
    {
     "expr": "reth_levm_db_latency_us{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "db_latency - P({{quantile}})"
    }
   ]
  },
  {
   "title": "End-to-End Throughput(Mgas/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "expr": "rate(reth_pipe_exec_layer_total_gas_used{instance=\"$instance\"}[$__rate_interval]) / 1000000",
     "legendFormat": "Throughput(Mgas/s)"
    }
   ]
  },
  {
   "title": "Commit Block Time Diff",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_finish_commit_time_diff{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "block_commit_time_diff"
    }
   ]
  },
  {
   "title": "Verify Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_verify_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "verify_block_duration"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_recv_block_time_diff{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "recv_block_time_diff - P({{quantile}})"
    }
   ]
  },
  {
   "title": "Filter Txs Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_filter_transaction_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "filter_transaction_duration"
    }
   ]
  },
  {
   "title": "Make Canonical Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_make_canonical_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "make_canonical_duration"
    }
   ]
  },
  {
   "title": "Block Persistence Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_consensus_engine_persistence_save_duration_per_block_seconds{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "persistence_block_duration - P({{quantile}})"
    },
    {
     "expr": "sum(rate(reth_consensus_engine_persistence_save_duration_per_block_seconds_sum{instance=\"$instance\"}[$__rate_interval])) / sum(rate(reth_consensus_engine_persistence_save_duration_per_block_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "persistence_block_duration_avg"
    },
    {
     "expr": "reth_storage_wait_persist_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "block_wait_persist_duration - P({{quantile}})"
    },
    {
     "expr": "reth_consensus_engine_persistence_persist_commit_duration_seconds{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "persistence_commit_duration - P({{quantile}})"
    },
    {
     "expr": "reth_consensus_engine_persistence_prune_before_duration_seconds{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "prune_duration - P({{quantile}})"
    }
   ]
  },
  {
   "title": "Cached Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_storage_latest_persist_block_number{instance=\"$instance\"}",
     "legendFormat": "persist_block_height"
    },
    {
     "expr": "reth_storage_latest_merged_block_number{instance=\"$instance\"}",
     "legendFormat": "merged_block_height"
    }
   ]
  },
  {
   "title": "Cached Block Height",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_storage_latest_merged_block_number{instance=\"$instance\"}",
     "legendFormat": "merged_block_height"
    },
    {
     "expr": "reth_storage_latest_persist_block_number{instance=\"$instance\"}",
     "legendFormat": "persist_block_height"
    },
    {
     "expr": "reth_storage_latest_eviction_block_number{instance=\"$instance\"}",
     "legendFormat": "eviction_block_height"
    }
   ]
  },
  {
   "title": "Cache Eviction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_storage_eviction_duration{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "eviction_duration"
    }
   ]
  },
  {
   "title": "Process Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_end_process_block_number{instance=\"$instance\"}",
     "legendFormat": "stored_block_height"
    },
    {
     "expr": "reth_pipe_exec_layer_start_process_block_number{instance=\"$instance\"}",
     "legendFormat": "merged_block_height"
    }
   ]
  },
  {
   "title": "Subpool Transaction Count",
   "type": "timeseries",
   "description": "Tracks the number of transactions in the various transaction pool sub-pools",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "reth_transaction_pool_pending_pool_transactions",
     "legendFormat": "Pending({{instance}})"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_transactions",
     "legendFormat": "Queued{{instance}}"
    }
   ]
  },
  {
   "title": "Process Block Height",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_pipe_exec_layer_start_process_block_number{instance=\"$instance\"}",
     "legendFormat": "start_process_block_height"
    },
    {
     "expr": "reth_pipe_exec_layer_end_process_block_number{instance=\"$instance\"}",
     "legendFormat": "end_process_block_height"
    }
   ]
  },
  {
   "title": "Nested Hash Stage Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "reth_nested_hash{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "{{process}} - P({{quantile}})"
    }
   ]
  },
  {
   "title": "History Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true
  },
  {
   "title": "Execution&Merkle Stage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_sync_execution_execution_histogram{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution_per_block(P{{quantile}})"
    },
    {
     "expr": "reth_history_sync_merkle_time_per_block{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "merkle_per_block(P{{quantile}})"
    }
   ]
  },
  {
   "title": "Execution Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "reth_sync_execution_gas_per_second{instance=\"$instance\"}",
     "legendFormat": "execution_throughput"
    },
    {
     "expr": "reth_history_sync_execution_throughput{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "smooth_throughput(P{{quantile}})"
    }
   ]
  },
  {
   "title": "block kv entries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "reth_table_block_updated_entries{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "{{table}}(P{{quantile}})"
    }
   ]
  },
  {
   "title": "RocksDB Write Stall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "reth_rocksdb_is_write_stopped{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "is_write_stopped"
    },
    {
     "expr": "reth_rocksdb_num_immutable_mem_table{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "num_mem_table"
    },
    {
     "expr": "reth_rocksdb_mem_table_flush_pending{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "is_flush_pending"
    },
    {
     "expr": "reth_rocksdb_num_files_at_level0{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "num_files_level0"
    }
   ]
  },
  {
   "title": "RocksDB Write Stall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "reth_rocksdb_actual_delayed_write_rate{quantile=\"$quantile\", instance=\"$instance\"}",
     "legendFormat": "delayed_write_rate"
    }
   ]
  },
  {
   "title": "Table Write Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_save_blocks_time{instance=\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "{{process}}(P{{quantile}})"
    }
   ]
  }
 ]
}